### ISSUE TITLE
rqrcode v1 changes API

### ISSUE THREAD

**Issue by boutil** [rcode5/qr4r#3]
Hi,

starting from its v1, the class to create new QR codes is in the RQRCodeCore module instead of RQRCode. It is possible to require only rqrcode_core >= 0.1 instead of rqrcode in the gemspecs and lib/rq4r.rb.

**Comment by bunnymatic** [comment]
Yes - good idea.  I will try to get to it, but i'm happy to look at a PR if you want to submit one.

**Comment by bunnymatic** [comment]
I started looking into it.  We need more than just `core` because the main `RQRCode` provides the `as_png` and other formats.  

This doesn't mean we shouldn't upgrade but it'll take a little work.  The api has changed.  I'll work on an update and it'll certainly be a version bump.  Just FYI.

**Comment by bunnymatic** [comment]
It's clearly been a while since I looked at this code.  I think you're right that we don't actually need any of the RQRCode stuff, just the core.   More as it happens.

**Comment by bunnymatic** [comment]
I've released version 0.6.0 which fixes this issue.

**Comment by boutil** [comment]
Thanks a lot!
